#!/usr/bin/env bash
# Quick setup guide - run these commands on your Mac

echo "==================================================================="
echo "  NIX DOTFILES SETUP - Follow these steps"
echo "==================================================================="
echo ""
echo "1️⃣  Create your config directory:"
echo "   mkdir -p ~/.config/nix-config"
echo "   cd ~/.config/nix-config"
echo ""
echo "2️⃣  Download your config files (place all downloaded files here)"
echo ""
echo "3️⃣  Update flake.nix - IMPORTANT!"
echo "   Open flake.nix and change 'islamtayeb' to your actual username"
echo ""
echo "4️⃣  Update home.nix git config - IMPORTANT!"
echo "   Open home.nix and update git userName and userEmail"
echo ""
echo "5️⃣  Initialize git repo:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo ""
echo "6️⃣  Create GitHub repo and push:"
echo "   gh repo create dotfiles --private --source=. --remote=origin --push"
echo "   # Or manually: git remote add origin <your-repo-url>"
echo "   # git push -u origin main"
echo ""
echo "7️⃣  Run installation:"
echo "   chmod +x *.sh"
echo "   ./install.sh"
echo ""
echo "8️⃣  Restart your terminal"
echo ""
echo "9️⃣  Install tmux plugins:"
echo "   tmux"
echo "   # Press Ctrl-l then Shift-I"
echo ""
echo "🔟 Open nvim and wait for LazyVim to install plugins"
echo ""
echo "==================================================================="
echo "  OPTIONAL: Auto-sync setup"
echo "==================================================================="
echo ""
echo "Setup automatic push to GitHub every 30 min:"
echo "   ./setup-cron.sh"
echo ""
echo "On other machines, setup auto-pull every hour:"
echo "   ./setup-cron.sh"
echo ""
echo "==================================================================="
echo "  NEW MACHINE SETUP"
echo "==================================================================="
echo ""
echo "1. Install Nix:"
echo "   sh <(curl -L https://nixos.org/nix/install)"
echo ""
echo "2. Enable flakes:"
echo "   mkdir -p ~/.config/nix"
echo "   echo 'experimental-features = nix-command flakes' > ~/.config/nix/nix.conf"
echo ""
echo "3. Clone your dotfiles:"
echo "   git clone <your-repo-url> ~/.config/nix-config"
echo "   cd ~/.config/nix-config"
echo ""
echo "4. Update flake.nix for this machine's username/hostname"
echo ""
echo "5. Run:"
echo "   ./install.sh"
echo ""
echo "==================================================================="
